### ISSUE TITLE
How to set Timestamp

### ISSUE THREAD

**Issue by morenoh149** [segmentio/analytics-go#109]
I'd like to specify a timestamp at which the event occurred. See https://segment.com/docs/spec/common/#timestamps

Can anyone confirm if the below code properly sets the `timestamp` field? And what would I see in the segment UI?
```go
client.Track(&Track{
		Event:  "my event",
		UserId: 1234,
		Properties: map[string]interface{}{
			"foo":      foo,
		},
		Message: analytics.Message{
			Timestamp: time.String(),
		},
	})
```
would this set the `orignalTimestamp` field? I'm seeing that has a timestamp in a different format in segment using the above code.

**Comment by f2prateek** [comment]
Sorry for the delay, but that looks correct to me. Our API will coerce the timestamp you send for the `timestamp` field, but the `originalTimestamp` will be preserved. Can you share an example of what you send and what it looks like in Segment?

for future reference, support questions like this are best sent to friends@segment.com who'll reply faster than on GitHub!

**Comment by morenoh149** [comment]
I think we're good on this for now.
