### ISSUE TITLE
Specify http client timeout

### ISSUE THREAD

**Issue by ottob** [segmentio/analytics-go#111]
https://github.com/segmentio/analytics-go/blob/master/analytics.go#L155
`c.Client.Timeout = 10 * time.Second`

This seems to be best practice.

You can test with this program:
```
package main

import (
  "fmt"
  "log"
  "net/http"
  "net/http/httptest"
  "time"
)

func main() {
  svr := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
    time.Sleep(time.Hour)
  }))
  defer svr.Close()

  fmt.Println("making request")

  c := http.DefaultClient
  // c.Timeout = 10 * time.Second
  _, err := c.Get(svr.URL)
  if err != nil {
    log.Fatalln(err)
  }

  fmt.Println("finished request")
}
```
With and without the Timeout line.

https://medium.com/@nate510/don-t-use-go-s-default-http-client-4804cb19f779#.wxbmr3nqi

**Comment by f2prateek** [comment]
This is on the `v3.0` branch by default https://github.com/segmentio/analytics-go/commit/af3757dc12b9c59f66c16c0404d89c3a3d061330.

For older versions, you can set the http client manually https://github.com/segmentio/analytics-go/blob/master/analytics.go#L121.

I'd recommend using the 3.x release. Open to accepting a PR to fix this on `master` as well. Here's how we did it in 3.x https://github.com/segmentio/analytics-go/commit/af3757dc12b9c59f66c16c0404d89c3a3d061330

**Comment by ottob** [comment]
Ok, I will use `v3.0`. Thanks for the hint.
