### ISSUE TITLE
The build is broken

### ISSUE THREAD

**Issue by yefim** [segmentio/analytics-go#116]
Please fix it :(

**Comment by f2prateek** [comment]
Hmm.. can you clarify further? https://circleci.com/gh/segmentio/analytics-go/tree/v3.0 is working as expected.

**Comment by yefim** [comment]
@f2prateek  `master` isn't :( we import segment like this:
``` go
import (
    analytics "github.com/segmentio/analytics-go"
)
```

and that fetches the broken `master`

**Comment by f2prateek** [comment]
Hmm.. I see our CI is broken, but that looks to be a CI configuration issue.

Everything works locally for me.

```

  13:17:29 as prateek on Thor-MBP in ~/dev/src/github.com/segmentio/analytics-go at master(*)
→ git remote update
Fetching origin

  13:17:37 as prateek on Thor-MBP in ~/dev/src/github.com/segmentio/analytics-go at master(*)
→ git pull
Already up-to-date.

  13:17:39 as prateek on Thor-MBP in ~/dev/src/github.com/segmentio/analytics-go at master(*)
→ go test ./...
ok  	github.com/segmentio/analytics-go	5.023s
?   	github.com/segmentio/analytics-go/cli	[no test files]
?   	github.com/segmentio/analytics-go/examples	[no test files]
```

Can you clarify what exactly is broken?

**Comment by yefim** [comment]
Yeah I can. After reading your docs, I think I figured it out. We were using the segment library like so:

``` go
client := analytics.New(segmentKey)

client.Track(&analytics.Track{
  ...
})
```

However `client.Track` has been deprecated it seems. Should we switch to `client.Enqueue` then `client.Close()` immediately after?

**Comment by f2prateek** [comment]
I see, I think the issue might have been that we switched the default branch to `v3.0`. I didn't realize that's what go get would pull (I assumed it always pulls master). I'll just changed the default branch back to `master` for now.

I would recommend switching to v3 when you can though.
There's a migration guide here https://segment.com/docs/sources/server/go/#migrating-from-v2
