### ISSUE TITLE
versioned urls

### ISSUE THREAD

**Issue by mcuadros** [segmentio/analytics-go#12]
My app code just get broken due to the 2.0 upgrade, can I sugguest use any versioned urls provider as [gopkg.in](http://labix.org/gopkg.in) or [gopkgs.com](http://gopkgs.com/)

**Comment by tj** [comment]
Hey sorry, totally missed this notification! You can already use `import "gopkg.in/segmentio/analytics-go.v2"` or vendor so builds don't break

**Comment by mcuadros** [comment]
thanks!
