### ISSUE TITLE
AppInfo failed for Unmarshal event type track

### ISSUE THREAD

**Issue by euskadi31** [segmentio/analytics-go#125]
Hi,

I use `analytics-go` for unmarshal json received by the webhook.

> json: cannot unmarshal number into Go struct field AppInfo.build of type string.

Could you normalized the type before sending it to the webhook or use the type `json.Number` for `AppInfo.Build` ?

see: https://golang.org/pkg/encoding/json/#Number

Thx

**Comment by f2prateek** [comment]
Hmmm... I don't know if we want to restrict this. The build doesn't always have to be a number, it could be something like "KY67". 

The issue you're really running into here is that this library is meant for sending data to segment, and not really menant to be used as a we hook receiver.

**Comment by euskadi31** [comment]
I know, the `json.Number` is a type alias of `string`, so "KY67" it's ok.

**Comment by f2prateek** [comment]
Sorry for the delay - but it feels incorrect to me that we would use a numeric type to indicate a value that could be an arbitrary string.
