### ISSUE TITLE
License and copyright

### ISSUE THREAD

**Issue by onlyjob** [segmentio/analytics-go#127]
Please consider adding a copyright statement.

Also "MIT" is an ambiguous license identifier let alone incorrect grant of license.
It would be best to add canonical URL to the full text of the license:

  https://opensource.org/licenses/MIT

as well as to commit full text of the license here, into the `LICENSE` file.

**Comment by onlyjob** [comment]
Yes, I'd say proper grant of license is a must as well as copyright statement.
I've found your library vendored in Mattermost without license at all (even though it was pinned to version 2.1.1)...

**Comment by f2prateek** [comment]
Done with fe449d569c914ede33754d117bd38526c65e48c9 and bbea922ea66f737f6af93fd8d02a33fe555fc82f

**Comment by onlyjob** [comment]
Thanks!
