### ISSUE TITLE
Timestamp is always overwritten

### ISSUE THREAD

**Issue by abourget** [segmentio/analytics-go#13]
`setTimestamp()` is always called upon `queue()`.. disregarding if we had previously set some value there.

Is it normal it uses `time.Now()` and not `time.Now().UTC()` ? so you need to make sure your system is configured with the same timezone as your integrations and all ?

**Comment by abourget** [comment]
Here's a quick and dirty patch to solve this:
```
diff --git a/analytics.go b/analytics.go
index e8600a5..d492695 100644
--- a/analytics.go
+++ b/analytics.go
@@ -26,7 +26,7 @@ var DefaultContext = map[string]interface{}{
 // Message interface.
 type message interface {
 	setMessageId(string)
-	setTimestamp(string)
+	setTimestamp(*Client)
 }
 
 // Response from API.
@@ -206,7 +206,7 @@ func (c *Client) Track(msg *Track) error {
 // Queue message.
 func (c *Client) queue(msg message) {
 	msg.setMessageId(c.uid())
-	msg.setTimestamp(timestamp(c.now()))
+	msg.setTimestamp(c)
 	c.msgs <- msg
 }
 
@@ -223,7 +223,7 @@ func (c *Client) send(msgs []interface{}) {
 	batch := new(Batch)
 	batch.Messages = msgs
 	batch.MessageId = c.uid()
-	batch.SentAt = timestamp(c.now())
+	batch.SentAt = ToTimestamp(c.now())
 	batch.Context = DefaultContext
 
 	b, err := json.Marshal(batch)
@@ -317,8 +317,10 @@ func (c *Client) log(msg string, args ...interface{}) {
 }
 
 // Set message timestamp.
-func (m *Message) setTimestamp(s string) {
-	m.Timestamp = s
+func (m *Message) setTimestamp(c *Client) {
+	if m.Timestamp != "" {
+		m.Timestamp = ToTimestamp(c.now())
+	}
 }
 
 // Set message id.
@@ -327,7 +329,7 @@ func (m *Message) setMessageId(s string) {
 }
 
 // Return formatted timestamp.
-func timestamp(t time.Time) string {
+func ToTimestamp(t time.Time) string {
 	return strftime.Format("%Y-%m-%dT%H:%M:%S%z", t)
 }
```

**Comment by f2prateek** [comment]
Have you run into any issues with the current setup? For some context, each outgoing message is stamped with a `sentAt` timestamp just before being uploaded, and our servers stamp it with `receivedAt`. These two are use to correct the local clock skew and and normalize the `timestamp` field along with it.

**Comment by calvinfo** [comment]
Oh, I think the issue is that `setTimestamp` is being set regardless, even
if the message already has `Timestamp` set. If you end up sending a
historical import then it will overwrite, even thought the clock skew is
working properly.

**Comment by sperand-io** [comment]
ping! @f2prateek @calvinfo

the `send.go` program that we'll be shipping with analytics-php relies on passing timestamp explicitly.
