### ISSUE TITLE
Releases without v prefix breaks go mod.

### ISSUE THREAD

**Issue by chiliburger** [segmentio/analytics-go#134]
When trying to use `go mod` with golang v1.11 the `go mod` commands will not work with analytics-go after `v2.0.0` due to the `v` prefix being dropped from the releases. Using `go mod vendor` automatically sets the analytics-go version to `v2.0.0` in the `go.mod` file because `go mod` thinks that is the latest version. When setting the version to `3.0.0` in the `go.mod` file it generates a parse error.

```
go mod vendor
go: finding github.com/segmentio/analytics-go 3.0.0+incompatible
go: errors parsing go.mod:
go.mod:21: invalid module version "3.0.0+incompatible": unknown revision 3.0.0+incompatible
```

**Comment by f2prateek** [comment]
Thanks! I pushed a tag v3.0.0 (https://github.com/segmentio/analytics-go/releases/tag/v3.0.0), and we'll keep the v prefix going forwards to work with Go modules.

**Comment by f2prateek** [comment]
Thanks for testing! I'll close this out, but feel free to reopen if you run into other issues with go modules.

**Comment by chiliburger** [comment]
@f2prateek sounds good, thanks!
