### ISSUE TITLE
Event tracking: passing a pointer to `Enqueue` results in silent dropped events

### ISSUE THREAD

**Issue by philipithomas** [segmentio/analytics-go#145]
We just had a problem with our code while switching to the V3 api, and it resulted in dropped events with no other symptoms, errors, or logs. It turns out the problem was that we were passing a reference to the track. This passed linting and tests. It did not return an error. Its logs made it look like the event was successfully uploaded. 

This was broken:

```
err = client.Enqueue(&analytics.Track{

        // Event name is action + target, e.g. create_payment

        Event:  "test-event",

        UserId: userID,

    })

    if err != nil {

        panic(err)

    }
```

This one works:

```
err = client.Enqueue(analytics.Track{
        // Event name is action + target, e.g. create_payment

        Event:  "test-event",

        UserId: userID,

    })

    if err != nil {

        panic(err)

    }
```

My request: Can you add some checks to prevent this from silently happening in the future?

**Comment by f2prateek** [comment]
This has been fixed with #146
