### ISSUE TITLE
Missing Context.Direct

### ISSUE THREAD

**Issue by kke** [segmentio/analytics-go#171]
According to https://segment.com/docs/connections/sources/catalog/libraries/server/http-api/#collecting-ip-address : 

> When sending a HTTP call from a user’s device, you can collect the IP address by setting context.direct to true.

There seems to be no `Context.Direct` in analytics-go.

We're trying to get telemetry from a CLI app, but would rather not manually figure out and send the IP for geolocation in the `IP` field.

**Comment by kke** [comment]
It seems the `Extra` field can be used?

```go
	// This map is used to allow extensions to the context specifications that
	// may not be documented or could be introduced in the future.
	// The fields of this map are inlined in the serialized context object,
	// there is no actual "extra" field in the JSON representation.
	Extra map[string]interface{} `json:"-"`
```

So, I guess:

```go
ctx := &analytics.Context{
  Extra: map[string]interface{}{"Direct": true},
}
```

**Comment by prayansh** [comment]
@kke yup that looks like the correct way to go for now. We will try to add that as a first-class feature in our SDK sometime in the future
