### ISSUE TITLE
Question:  Offline/Development mode?

### ISSUE THREAD

**Issue by rtyer** [segmentio/analytics-go#20]
Is there a way to configure this library to noop the event send?  It's not a huge issue, but would be nice for no connectivity scenarios (train, etc) and to not put spurious events in the dev account.

Happy to submit a PR for this, but I thought I'd check for your thoughts first.

**Comment by f2prateek** [comment]
No, the best you can do is to override the endpoint to an in-memory server for testing, or use a different key for dev mode.

The library is designed for use in servers, so not sure if we should really we be worried about not having a network connection.

**Comment by achille-roussel** [comment]
@rtyer I think you could do it with the current version by setting the `Client` field to some mock HTTP client that doesn't actually send requests.

Let me know if that's working out for you and I'll close this issue.
