### ISSUE TITLE
Checking for error in track function

### ISSUE THREAD

**Issue by jsloyer** [segmentio/analytics-go#21]
Is there a way to check for an error in the `track` function?

**Comment by jsloyer** [comment]
I am getting some of the following errors in my logs and I would love to catch them and try the API call again.

```
2015/09/21 18:18:57 segment: error sending request: Post https://api.segment.io/v1/batch: net/http: TLS handshake timeout
2015/09/21 18:19:56 segment: error sending request: Post https://api.segment.io/v1/batch: net/http: TLS handshake timeout
```

**Comment by f2prateek** [comment]
unfortunately, not yet.

**Comment by jsloyer** [comment]
+1 on implementing this.  Kinda crucial for production to make sure data is flowing...  Is there a way to double check that data made it there instead?

**Comment by f2prateek** [comment]
Yeah it's tricky right now since without generics, we lose all the type information by the time we queue the message. We could report errors, but they wouldn't be any use unless we hand you back the original message with it as well.

**Comment by jsloyer** [comment]
Yeah valid point...  Can we put this on the roadmap to get implemented? 

Also, any other strategies for checking to make sure data arrived?

**Comment by f2prateek** [comment]
It is on our roadmap already, will be hard to do unless we break some APIs so we're kinda locked into this for now sorry.

As for testing, you could set up a webhook integration that your client can request events from. So your test would look like:
`test -> analytics-go lib -> api.segment.com -> webhook integration -> pulled by test`

**Comment by f2prateek** [comment]
As for your specific problem, you can now set a custom http client — https://github.com/segmentio/analytics-go/pull/26, so you could configure timeouts more appropriate for your use/servers.

**Comment by jsloyer** [comment]
Is there a way to retro-actively check this?

**Comment by f2prateek** [comment]
Not sure what you mean, try implementing the custom timeout and see if that solves your issue?
