### ISSUE TITLE
Interval is not configurable

### ISSUE THREAD

**Issue by f2prateek** [segmentio/analytics-go#36]
Although the interval is public and mutable, since we start the `loop` goroutine right away, clients can't actually change the interval.

**Comment by yields** [comment]
could do something along the lines of:

```
// Queue message.
func (c *Client) queue(msg message) {
        c.once.Do(c.startLoop)
	msg.setMessageId(c.uid())
	msg.setTimestamp(timestamp(c.now()))
	c.msgs <- msg
}
```

**Comment by f2prateek** [comment]
That could work!

Though I'd rather just make interval not mutable, and be passed as a configuration option during the client construction.

**Comment by yields** [comment]
agreed! -- a lot more clear as well, most go libs that i've seen so far use config structs.
