### ISSUE TITLE
Google App Engine compatibility

### ISSUE THREAD

**Issue by elsigh** [segmentio/analytics-go#37]
segment 2015/11/06 23:05:23 error sending request: Post https://api.segment.io/v1/batch: http.DefaultTransport and http.DefaultClient are not available in App Engine. See https://cloud.google.com/appengine/docs/go/urlfetch/

**Comment by elsigh** [comment]
Derp, I see that you can pass 
```client.Client = *urlfetch.Client(c)```

Worth mentioning I get the following error testing locally (but not an issue with the go implementation)

segment 2015/11/06 23:20:50 error sending request: Post https://api.segment.io/v1/batch: API error 6 (urlfetch: SSL_CERTIFICATE_ERROR): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

**Comment by f2prateek** [comment]
hmmm.. what do you mean by "testing locally (but not an issue with the go implementation)"?

**Comment by elsigh** [comment]
Fair question - it's using the local dev_appserver.py and maybe this is a byproduct of using *urlfetch.Client(c) in particular? I imagine otherwise that *everyone* using the go implementation would be getting this error.

**Comment by devilbags** [comment]
Came across this digging through Google.
I'm facing the same issue. Whenever try to make an HTTP POST request using Google's 'app engine/urlfetch' package, the local server gives me 
`(urlfetch: SSL_CERTIFICATE_ERROR): Host XXX.com returned an invalid certificate`

**Comment by f2prateek** [comment]
`host xxx.com`? is that your host or Segment's?

**Comment by elsigh** [comment]
Yeah, this problem went away for me once I pushed to a non dev_appserver (e.g. appcfg deploy)

**Comment by f2prateek** [comment]
Yeah my guess is it's the client complaining about your local/dev server missing certificates - they probably have an API to relax the certificate checking during development.

**Comment by improbable-luke** [comment]
Not tested, but this may stop your SSL cert errors on `dev_appserver`:
```
	c := &http.Client{
		Transport: &urlfetch.Transport{
			Context: ctx,
			AllowInvalidServerCertificate: appengine.IsDevAppServer(),
		},
	}
	client.Client = *c
```

**Comment by jlubawy** [comment]
I also stumbled upon this issue, see my solution to the problem here: https://code.google.com/p/googleappengine/issues/detail?id=12588

I think the SSL cert chain provided with the Go App Engine SDK is out of date.
