### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED trying to track an event

### ISSUE THREAD

**Issue by elsigh** [segmentio/analytics-go#38]
On AppEngine, using the urlfetch client, one gets:
```
segment 2015/11/09 23:34:31 error sending request: Post https://api.segment.io/v1/batch: API error 6 (urlfetch: SSL_CERTIFICATE_ERROR): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
```

The `fetch` method does take a `validate_certificate` flag which can be set to false (see https://cloud.google.com/appengine/docs/python/refdocs/google.appengine.api.urlfetch?csw=1#google.appengine.api.urlfetch.fetch).

Is there really a bad cert here?

**Comment by achille-roussel** [comment]
Hi @elsigh, are you still experiencing this issue?

**Comment by elsigh** [comment]
Nope
