### ISSUE TITLE
Calling close before sending anything blocks forever

### ISSUE THREAD

**Issue by paddie** [segmentio/analytics-go#43]
Hi, thanks for releasing this tool!

I had a weird issue when testing it, where it would block forever if you created a new client, and closed it without sending a single event (in my case a track event):

```golang
func main() {
    client := analytics.New("<segmentWriteKey>")
    client.Close()
}
```

**Comment by calvinfo** [comment]
Ah you're right–PR'd and we'll get it in shortly!

**Comment by paddie** [comment]
Thank you!

**Comment by achille-roussel** [comment]
Actually, I think there's a simple way to solve this problem that doesn't require making any API breaking changes:
```go
func (c *Client) Close() error {
    c.once.Do(c.startLoop)
    ...
}
```
That way we ensure that the goroutine is always started even if the client gets closed.

**Comment by f2prateek** [comment]
@achille-roussel Haha yup - that's what I suggested here - https://github.com/segmentio/analytics-go/pull/44#issuecomment-201913300, though it does feel like a bit of a hack.
