### ISSUE TITLE
Ability to set custom MessageId

### ISSUE THREAD

**Issue by nvcnvn** [segmentio/analytics-go#47]
We want to set our custom ID (uuid v1) but MessageId overrided when pushing to queue by calling setMessageId https://github.com/segmentio/analytics-go/blob/master/analytics.go#L371

Do segment have any restrict on MessageId format?

**Comment by calvinfo** [comment]
Nope, you can send messageIds in any format you want–though please be aware
that we *do* de-duplicate calls based upon messageId.

**Comment by nvcnvn** [comment]
Thanks for your reply,
Also I see a pull request for seting custom MessageID so this issue shuold be close I guess.
