### ISSUE TITLE
Pass values instead of pointers to send methods

### ISSUE THREAD

**Issue by achille-roussel** [segmentio/analytics-go#52]
@f2prateek 

What do you think about passing values instead of pointers to the send methods? Besides making the syntax heavier and putting more pressure on the compiler and GC I don't really see why this is done (we're not using the `nil` value for example and it would always cause a panic to pass `nil`, crashing at runtime instead of compile time).

Basically changing
```go
func (c *Client) Alias(a *Alias) error { ... }
```
to
```go
func (c *Client) Alias(a Alias) error { ... }
```
Let me know what you think about it?

**Comment by f2prateek** [comment]
Yeah I think passing values is the right way to go 👍 

unsure why we had pointer in the first place

**Comment by achille-roussel** [comment]
As I'm reading the code more in depth I think the pointers are here because of the `setMessageId(string)` and `setTimestamp(string)` of the `message` interface.

The actual types implement the interface on their pointer type because they extend the `Message` type which defines those methods on `*Message`...
I feel like this trick is really overkill to save a total of 10 lines of trivial code that would be repeated otherwise, especially because this is all internal implementation and we can easily write tests to make sure we're not introducing bugs there.

Anyway, thanks for your answer!

**Comment by calvinfo** [comment]
Sounds right to me for the reason, and I'm okay with the change.
