### ISSUE TITLE
Merging all send methods into one

### ISSUE THREAD

**Issue by achille-roussel** [segmentio/analytics-go#53]
@f2prateek 

I think we could make the client API simpler if we were merging all send methods into one `Send(interface{})` and doing a type-check internally to know what message has been passed, that we we could write things like:
```go
client.Send(analytics.Track{ ... })
client.Send(analytics.Page{ ... })
...
```
which is less redundant than
```go
client.Track(analytics.Track{ ... })
client.Page(analytics.Page{ ... })
```
and also makes the API simpler, therefore easier to document and learn?

The downside I'm seeing is that we lose the compile-time check that the program is passing valid types to the function, although we can get it back with a trick like this:
```go
type Event interface {
    // This method is unexported so only types defined in the analytics package can
    // implement this interface.
    path() string
}

type Alias struct { ... }

func (a Alias) path() string { return "/alias" }

// Expects a type that satisfies the Event interface
func (c *Client) Send(e Event) error { ... }
```

**Comment by f2prateek** [comment]
Yup I think a single enqueue would be better (as we do in the java library) https://segment.com/docs/libraries/java/.

**Comment by achille-roussel** [comment]
Cool! Yeah let's keep the naming as consistent across libraries and call it `Enqueue` then.

**Comment by f2prateek** [comment]
Cool, yeah I preferred `enqueue` in the Java library over `send` since it's clearer that the message is not uploaded right away.
