### ISSUE TITLE
Don't force using a log.Logger

### ISSUE THREAD

**Issue by achille-roussel** [segmentio/analytics-go#54]
@f2prateek 

Right now we allow configuring the client logger by defining a `*log.Logger` object that a client should use.
This does limit the loggers usable to the logger from the standard Go library but there are other logging libs out there that may be used and that we could integrate with.

We only use the `Printf` method of the logger object we receive, I think we could take one of these two approaches, which comes handy when integrating with unit tests as well:
- using an interface
```go
type Logger interface {
    Logf(string, ...interface{})
}

type Client struct {
    ...
    Logger Logger
}
```
- using a function
```go
type Client struct {
    ...
    Logf func(string, ...interface{})
}
```
I tend to like the first approach better as it's usually how it's done in Go, it also makes it easy to integrate with the unit tests logger:
```go
func TestX(t *testing.T) {
     client := analytics.New("write-key")
     client.Logger = t // cloud also be `client.Logf = t.Logf` with the other option
     ...
}
```
Go makes it also really easy to make functions implement single-method interfaces with tricks like this:
```go
type LoggerFunc func(string, ...interface{})

func (f LoggerFunc) Logf(format string, args ...interface{}) {
    f(format, args...)
}
...
client.Logger = analytics.LoggerFunc(logf)
```
so we could get the best of both worlds this way.

Let me know what you think about it.

**Comment by achille-roussel** [comment]
Having the method called `Logf` does make it incompatible with the standard logger, we could call the method `Printf` (which makes it then incompatible with the `testing` package... sounds like a design flaw), but we can work around with trick like:
- converting a standard logger to an `analytics.Logger`
```go
type Logger interface {
    // Compatible with the testing logger
    Logf(string, ...interface{})
}

func StdLogger(logger *log.Logger) Logger {
    return LoggerFunc(logger.Printf)
}
```
- converting a testing logger to an `analytics.Logger`
```go
type Logger interface {
    // Compatible with the standard logger
    Printf(string, ...interface{})
}

func TestingLogger(t *testing.T) Logger {
    return LoggerFunc(t.Logf)
}
```
I'd say I like the first approach better so it doesn't create a dependency on the `testing` package.

**Comment by f2prateek** [comment]
What if we just accepted an `io.Writer`?

**Comment by achille-roussel** [comment]
I think having the concept of a logger is better, that way the program can set a specific log format (with timestamps in a special format or prefixed with "segment" to make it easy to filter for example).

**Comment by f2prateek** [comment]
Cool makes sense - how about something that distinguishes b/w the log type.

```go
type Logger interface {
    Errorf(string, ...interface{})
    Printf(string, ...interface{})
}
```

Or a bit more complex as we do in the java library (https://github.com/segmentio/analytics-java/blob/master/analytics/src/main/java/com/segment/analytics/Log.java#L5-L11).

This gives more power, and lets users format the message depending on the error level (e.g. red for errors if a tty is attached).

**Comment by achille-roussel** [comment]
I'm down for a change of this kind but this interface is compatible with neither `testing.T` nor `log.Logger`. 
If we change it to:
```go
type Logger interface {
    Logf(string, ...interface{})
    Errorf(string, ...interface{})
}
```
It is then compatible with `testing.T` and has the side effect of making the test fail if `Errorf` is called (which may be cool, or may be weird if `Errorf` isn't called if verbose is set to false for example).

I what we need the most is a compatibility shim to the standard logger but it only has `Printf`, `Panicf` or `Fatalf`: https://golang.org/pkg/log/
We need to define what the mapping would be then, do we want something like this:

| analytics | log |
| ------------ | ---- |
| Logger.Logf | Logger.Printf |
| Logger.Errorf | Logger.Fatalf |

or something like this (I like it better as it doesn't crash the program):

| analytics | log |
| ------------ | ---- |
| Logger.Logf | Logger.Printf("INFO: " + format, args...) |
| Logger.Errorf | Logger.Printf("ERROR: " + format, args...) |

**Comment by f2prateek** [comment]
Yeah agreed, definitely prefer the latter in that case.
