### ISSUE TITLE
Closing a client twice will block

### ISSUE THREAD

**Issue by achille-roussel** [segmentio/analytics-go#55]
@f2prateek 
@calvinfo 

Currently the `Close` method is not idempotent, and worst it blocks the program's execution if called more than once, see:
```go
// Close and flush metrics.
func (c *Client) Close() error {
    c.quit <- struct{}{}
    close(c.msgs)
    <-c.shutdown
    return nil
}
```
The issue is that nothing is reading from the `c.quit` channel anymore once the client has been closed.

One way of solving this is to close the `c.quit` channel from the client's goroutine before it terminates, but this would cause writing to the channel to panic on the second call of `Close`, so we have to protect this with a recover call, basically changing the method to something like this:
```go
// Close and flush metrics.
func (c *Client) Close() error {
    defer func() {
        // Always recover, a panic could be raised if c.quit was closed which means
        // the Close method was called more than once.
        recover()
    }()
    c.quit <- struct{}{}
    close(c.msgs)
    <-c.shutdown
    return nil
}
```
What do you guys think about it?

**Comment by f2prateek** [comment]
I don't think it's a huge issue that the 2nd invocation blocks. https://golang.org/pkg/io/#Closer `The behavior of Close after the first call is undefined. Specific implementations may document their own behaviour.` We can document that it blocks/panics. IMHO it's an error to call it multiple times.

**Comment by calvinfo** [comment]
I also don't think it's a huge issue, but I'm +1 to making it not block if
we are able to do it easily just to save folks some grief. It seems like
it'd be an easy mistake to have a graceful shutdown handler which calls
close multiple times with some backoff.

**Comment by f2prateek** [comment]
Yup agreed, if there's an easy fix for us +1 to us doing that, if not then documenting it should be good.

**Comment by achille-roussel** [comment]
Agree it's not a huge issue, but we could make the code much more flexible with a small change (basically 2 lines of code).

Also agree the `io.Closer` interface does not enforce the behavior but I strongly feel like it's a bad design decision to say *we're gonna block the program*.
About panicking, that would be an option but Go good practices recommend to avoid letting panics pass package boundaries as it makes it harder for developers to reason about the program flow.

I'll be happy if we want to return an error when `Close` is called more than once just to express that the client was already closed.
