### ISSUE TITLE
Use time.Time to represent timestamps in data structures

### ISSUE THREAD

**Issue by achille-roussel** [segmentio/analytics-go#56]
@f2prateek 
@calvinfo 

Currently the timestamp and sentAt fields have a `string` type in the data structures (`Alias`, `Track`, ...), this is not very handy and developers have to refer to the HTTP API documentation to understand what format this should be in (which isn't linked from the Go code).

I feel like we should use `time.Time` for these fields and take care of the serialization internally so we take the burden off of the developers using the library and leverage the compiler to verify that they're using valid values (basically a time value, right now they could inject whatever string format in there).

Let me know what you think about it?

**Comment by calvinfo** [comment]
Strong +1

**Comment by f2prateek** [comment]
Yup agree, `time.Time` is better (we do this in java, android too) and we don't even need any magic for serialization because the default format is iso 8601.

**Comment by achille-roussel** [comment]
Yep, although the Go serializer uses nanosecond precision while the JS serializer uses milliseconds, any change this is gonna be an issue server side?

**Comment by calvinfo** [comment]
Should be good, as long as it serializes to an ISO timestamp. Node just
drops the extra precision.
