### ISSUE TITLE
Use http.RoundTripper instead of http.Client

### ISSUE THREAD

**Issue by achille-roussel** [segmentio/analytics-go#57]
@f2prateek 

We're currently allowing the `analytics.Client` to configure the HTTP client it uses to connect to our API. While this is great it offers more flexibility than is usually needed.

http.Client is not a generic type and it allows configuring more than we need/want. For example it manages cookies, redirections, timeouts... things that we potentially want to have full control over.

My understanding is that we want to allow overriding the transport layer (let's say to do unit tests that don't actually connect over the network, use a different pooling policy, etc...) but the rest of the setup should be handled by the library.

I think we could change this to have a `Transport http.RoundTripper` field in the `analytics.Client`, which is an interface so consumers of the library can really inject whatever they want here.

Thoughts?

**Comment by f2prateek** [comment]
Interesting - though I feel like we do want to give the application the control over timeouts, no?

**Comment by achille-roussel** [comment]
We probably should give the app the ability to set some sort of timeout but there's value in hiding the per-request timeout in the library.

We have a more complex upload model than a simple HTTP request - we do retries on failures with exponential back off, I'm not really sure what it means to say that the operation timed out in that case. Maybe want we should let the user configure is a full upload-with-retry timeout, per-request doesn't really make sense especially because the program has no idea of the size of the request and can't make a very educated decision.

Better than a timeout may be offering a lower limit for the upload rate, so the application says *I want uploads to not be slower than 1KB/s* and we adjust the timeout internally based on that and the size of the request.
I feel like keeping the actual request timeout as *implementation defined* would let us manipulate it in ways that we know would better help getting the data to Segment (like doing QoS on the connection and adjusting the timeout based on that).

**Comment by f2prateek** [comment]
Cool, SGTM!
