### ISSUE TITLE
Get rid of the Message type

### ISSUE THREAD

**Issue by achille-roussel** [segmentio/analytics-go#58]
@f2prateek 

I think we should get rid of the `Message` type and the inheritance-like approach in the current implementation and instead inject the `MessageId`, `SentAt` and `Timestamp` field into each object.

The thing that's bugging me the most is the exported `Type` field and the `message` interface hack. `Type` is only ever used internally and doesn't need to be exposed and we wouldn't even need it internally if we took the approach defined in #53

**Comment by f2prateek** [comment]
SGTM, I'm not sure how the other approach will work for the JSON serialization though (we need an exported `Type` field to make it work IIRC).

**Comment by achille-roussel** [comment]
Hm... what is the `type` field used for in the request?
The HTTP API documentation doesn't talk about it at all. All I'm seeing is an `action` field which is set to `alias`, `track`...

**Comment by f2prateek** [comment]
You're right - the `action` field should be `type` and the docs are wrong (https://segment.com/docs/libraries/http/#import).

https://github.com/segmentio/api-transforms/blob/166e0a3f7ca2edadfd159c02722f5bc909d15178/lib/transform.js#L459-L470

**Comment by f2prateek** [comment]
(TLDR is action is deprecated and we call it type now)

**Comment by f2prateek** [comment]
Updating docs too https://github.com/segmentio/site-docs/pull/1305

**Comment by achille-roussel** [comment]
OK 👍 

So I still think the sudo-inheritance makes things more complex for no reason, to solve the `Type` field problem we could do one of the following:

- don't serialize the exported types and instead make them internally convertible to serializable types, for example having `func (a Alias).serializable() interface{} { return alias{ Type: "alias", ... } }`, so we don't expose the `Type` field and `alias` is the serializable type... may be overkill.

- document that the `Type` field shouldn't be considered public and will be overwritten.

What I like about the first option is it's the *purest* for consumers of the library, they don't see what they don't need to know.
What I don't like about it is it does require a bunch more code to be written in the library's implementation... but with proper unit testing we could keep that complexity under control.

I guess we'll need to have a prototype to make a good decision.

**Comment by f2prateek** [comment]
yeah it's tricky for sure - I ended up going the 2nd route in the other libraries like Java since 1) we can make the fields immutable (not possible nicely Go if exported) and 2) reduces the need for us to have multiple types (internal and external) for the same thing.

**Comment by f2prateek** [comment]
Maybe we could do something like this.

```go
// Usage:
analytics.Track('event').Enqueue()

analytics.Track('event').Properties(...).Options(...).Timestamp(...).Enqueue()
```

```go
// Implementation:
func (c *Client) Track(event string) *TrackBuilder {
  return &TrackBuilder{
    client: c,
    event: event
  }
}

type TrackBuilder struct {
  client *Client
  event string
  properties map[string]interface{}
  ... // options, timestamp, etc.
}

func (b *TrackBuilder) Properties(properties map[string]interface{}) *TrackBuilder {
  b.properties = properties
  return b
}

// Similar setters for options, timestamp, etc.

func (b *TrackBuilder) Enqueue() {
  b.client.send(map[string]interface{}{
    "event": b.event,
    "properties": b.properties,
    "type": "track",
    ...
  })
}
```

**Comment by f2prateek** [comment]
i.e. internally use map[string]interface{} since we only need it for serialization.

**Comment by f2prateek** [comment]
That being said, there is one small advantage of exposing the internal fields. People could use it as a Go representation of our Json API and write their own libraries. 

e.g. In the Java library, we have module that is simply the [service definition](https://github.com/segmentio/analytics-java/blob/master/analytics-core/src/main/java/com/segment/analytics/http/SegmentService.java) and the model types that is a Java representation of the Json — https://github.com/segmentio/analytics-java/tree/master/analytics-core/src/main/java/com/segment/analytics/messages.

We use this to build the the [real library](https://github.com/segmentio/analytics-java/tree/master/analytics/src/main/java/com/segment/analytics) which handles batching/flushing/etc. But this gives users the option to write their own client library using just the Java value types.

**Comment by achille-roussel** [comment]
I'm no big fan of the chaining construction of maps, I know it's used extensively in some languages, I feel like we're lucky enough in Go to have a nice declarative way of initializing structures that we should use it.

That's an interesting point you raise (about making other libs with the data types), although I think there are many ways to solve it in Go that doesn't require exposing the serialization requirements.
One could implement the `[json.Marshaler](https://golang.org/pkg/encoding/json/#Marshaler)` interface on all exported types so they can be serialized to JSON without knowing what exactly needs to be the representation.
Another approach could be to implement the `[io.WriterTo](https://golang.org/pkg/io/#WriterTo)` interface so it can be serialized without even knowing that it has to be done by a JSON encoder.

**Comment by f2prateek** [comment]
Sounds great! I think this definitely gives us a few ideas to play with and try out.
