### ISSUE TITLE
Pulling config from file or environment

### ISSUE THREAD

**Issue by achille-roussel** [segmentio/analytics-go#61]
@f2prateek 
@calvinfo 

As part of #48 I mentioned we could pull the write-key or other configuration properties from a config file or environment variables (the way the AWS SDKs work).

I'm rather in favor of it, I think it often handy to have config easily changed without affecting the library's API, it often makes development and operations easier.

For example, we currently require the write-key to be passed to the client's constructor, which means a program that wants to define those values from environment variables or a config file has to implement the logic itself to then pass the settings to the constructor.

The decision here is really defining what the signature of a function like `analytics.NewWithConfig` would be:
- not using config files or environment variables
```go
type Config struct {
    ...
}

func NewWithConfig(writeKey string, config Config) Client {
    ...
}
```
- with config files or environment variables
```go
type Config struct {
    Key string
    Dir string // path to the segment config directory, would default to something like ~/.segment
    ...
}

// In that case the key is not required anymore, if zero it will be loaded from
// the environment or config file.
// Here we should really return an error if something goes wrong or if no key
// could be found so the program has a way to check that it's not behaving
// properly.
func NewWithConfig(config Config) (Client, error) {
    ...
}
```
Let me know what you guys think about this.

**Comment by f2prateek** [comment]
Personally I wouldn't like to do this. I think having a single way of doing things is optimal - and a constructor parameter is the most flexible way.

Consider this case, copies a production service which defines the segment key in a config file (from copy pasting from a different service). They read our docs and also add it as an env var. But they misname the env var (SEGENT_KEY). Now they're confused why the `SEGENT_KEY` var is not being picked up correctly (or worse, miss it and see events go to the wrong project).

Adding multiple sources for the key in our library also adds unnecessary complexity for us - read from a file, read from flag, read from environment, etc. Plus it's not hard to simply have people do `os.Getenv("SEGMENT_KEY")` if they'd prefer to do so so it doesn't really improve the API significantly.

**Comment by achille-roussel** [comment]
Sounds fair to me, let's not go this way then.

**Comment by calvinfo** [comment]
I'm agreed, I think the only reason AWS can get away with this is there are
*so* many different client libs and 3rd party tools out there that can
leverage the ENV vars or files separately.
