### ISSUE TITLE
Drop godep dependency

### ISSUE THREAD

**Issue by achille-roussel** [segmentio/analytics-go#69]
@f2prateek 
@calvinfo 

Hey guys, what do you think about relying on the standard vendoring system (available from Go 1.5+ with `GO15VENDOREXPERIMENT=1` set, and enabled by default in Go 1.6)?

Circle-CI is building with Go 1.6 already according to [this](https://circleci.com/docs/build-image-trusty/).

**Comment by f2prateek** [comment]
Yeah +1 from me! I'd love to move to the vendor directory, though I know we haven't in internal projects for various reasons.
