### ISSUE TITLE
v1/batch vs. v1/import

### ISSUE THREAD

**Issue by paddie** [segmentio/analytics-go#71]
The documentation doesn't really mention anything about `v1/batch` as an endpoint, but rather `v1/import`. The payload seems to be the same for both of them as documented here: [import](https://segment.com/docs/libraries/http/#import)

**Comment by f2prateek** [comment]
Indeed, we actually have 3 that do the same thing [(`/v1/batch`, `/v1/import` and `/v1/b`)](https://github.com/segmentio/tracking-api/blob/9b18d72c74944369243da16a12e255b959640b19/message/message.go#L26-L31). @yields not sure which is the official one? I'm assuming `import` since it's documented.

**Comment by achille-roussel** [comment]
I think we're using either of these across different libraries from what I can read, I haven't heard of any plan to get rid of any of these endpoints so let's not fix something that isn't broken?

**Comment by calvinfo** [comment]
We should go with /v1/batch for everything. /v1/import was the historical
name that we never really phased out, but since both endpoints support
historical data, batch is what makes sense.

**Comment by achille-roussel** [comment]
I'll close this issue, ideally we should update the HTTP API documentation but this isn't directly related to the Go library.
Feel free to reopen if anything was left unanswered.
