### ISSUE TITLE
Add a Traits type

### ISSUE THREAD

**Issue by achille-roussel** [segmentio/analytics-go#75]
@f2prateek 

Following the idea in #59, the traits type is also documented to have a specific format in https://segment.com/docs/spec/identify/#traits

Should we introduce a `Traits` type to make the type of information managed by this type more self explanatory and get type safety checks at compile time?

**Comment by f2prateek** [comment]
I don't believe that traits are standardized like context. https://cloudup.com/c3KQOQu-Owa

Like properties, some fields are standardized, but it is definitely acceptable for customers to be able to set their own keys for traits.

**Comment by achille-roussel** [comment]
The documentation says *The following is all the reserved traits we’ve standardized:*, how about taking the same approach that we have with the `Context` type, defining the structure with all fields from the specs and adding an `Extra` map for extensions?

**Comment by f2prateek** [comment]
Traits are certainly meant to be a free form dictionary and this is a very common use case - so I wouldn't like to hide custom ones behind the `Extras`. I think it degrades the API (didn't matter much in the context because there is a very limited number of cases when you'd use something beyond what we've documented). 

```
analytics.Traits{
Age: 21,
Extras: map[string]interface{}{
  "plan": "developer",
},
}
```

vs.

```
map[string]interface{}{
  "age": 21,
  "plan": "developer",
}
```

**Comment by achille-roussel** [comment]
OK.

Yeah as I'm reading more in details, pretty much everything is a string except dates but it says the API is flexible and accepts different formats... It doesn't look like there's much needs to do sanity checks client side.

Thanks for the insights!

**Comment by f2prateek** [comment]
For this, I like what we've done in the Android library the best - we've let users use a map and the traits type independently. This gives users the option to use the regular Java Map API:

```java
new HashMap<>().put("age", 21).put("plan", developer")
```

Or use the specific implementation of our `Map` type (traits) which adds type safe setters for the spec'd fields.

```java
new Traits().putAge(21).put("plan", developer")
```

And then this works great things like properties as well:
```java
new Properties().putRevenue(21.09).putCurrency("usd").put("custom", "custom");
```

**Comment by achille-roussel** [comment]
Hm interesting, I'm gonna think about it a little bit and see if we can figure something that works well in Go.
