### ISSUE TITLE
Add Screen type

### ISSUE THREAD

**Issue by achille-roussel** [segmentio/analytics-go#76]
@f2prateek 

There has been no `Screen` type in the Go library until now, I initially thought the intent was to not have this abstraction because it's not a mobile device but actually I'm seeing that the Java library exposes it.

Should we add `analytics.Screen` as well to get to feature parity with other server-side libs?

**Comment by calvinfo** [comment]
+1 from me. It's definitely unusual, but for folks who record views on
their mobile app and send to their go backend/pipeline, I think it makes
sense.

**Comment by f2prateek** [comment]
Yup, we should!
