### ISSUE TITLE
Flushing pending messages when the client is closed can exceed the batch size

### ISSUE THREAD

**Issue by achille-roussel** [segmentio/analytics-go#80]
When a client gets closed it stops accepting new messages and flushes the ones that had been queued already.

Unfortunately all pending messages are flushed at once which means the batch size isn't respected and it's possible to be sending more messages than the configured batch size.

**Comment by f2prateek** [comment]
I think this is OK. The batch size is simply a hint to the library, we can deviate from it. e.g. we flush on a timer - so a batch may have items < the batch size too.

**Comment by achille-roussel** [comment]
OK, my understanding was that it was a hard limit, I guess if we implement #81 this is what will set the hard limit then.
