### ISSUE TITLE
Predict the size of the batched request

### ISSUE THREAD

**Issue by achille-roussel** [segmentio/analytics-go#81]
@f2prateek 
@calvinfo 

I noticed that we don't check for the size of the serialized JSON before sending a request and only rely on the batch size (number of in-flight messages).
Is there a historical reason for that or did we just not spend the time implementing it because limiting the message count works well enough?

**Comment by f2prateek** [comment]
Yeah we should. Only the Android library does this (it splits the batch into payloads of ~500kb).

**Comment by calvinfo** [comment]
No, we should. In practice it works fairly well, but it's something we
should check with certainty from the client libs.
