### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by achille-roussel** [segmentio/analytics-go#82]
It would make it a better experience for readers to have a README file with a bit more content (quick start, examples, links, etc...)

**Comment by f2prateek** [comment]
The Readme should just point to our hosted docs. We could add sections with links to sections in our docs, but I'd rather not have duplicated content. Otherwise we have to keep them in sync in three places (godoc, segment, readme).

**Comment by achille-roussel** [comment]
I didn't mean to duplicate content, neither to make the Readme long, just make it a bit more guiding (link to specs, http API, godoc...) plus have one or two examples that can be just copy/pasted by someone who wants to start quickly without having to go through the entire doc.

**Comment by calvinfo** [comment]
I'm +1 to that across all of our libs. I think we can make the readmes
significantly more useful while also not duplicating content. Even just
linking to the quickstart, full reference, godocs, and having a full
install cmd would be helpful.
