### ISSUE TITLE
Release 3.0.0

### ISSUE THREAD

**Issue by achille-roussel** [segmentio/analytics-go#95]
- [x] Make migration guide from 2.x to 3.0
- [x] Update site documentation
- [ ] Update debugger _pretty_ examples
- [ ] Update History.md

**Comment by f2prateek** [comment]
We're doing this now!

**Comment by kevpie** [comment]
Is it possible to set the 3.0 branch as your Default Branch so that the Github experience shows off the great work done in it?  Search and default nav would stop presenting very old code.

**Comment by f2prateek** [comment]
I tried that, unfortunately it breaks people's build without warning https://github.com/segmentio/analytics-go/issues/116.

**Comment by kevpie** [comment]
I hear you.  If they don't have version pinning they are playing with fire anyways. 
2 ideas, and you don't have to use either.
1)  Create a new repo and do all the new dev there.
2) Create a new repo and move the old master there and then a user who is go getting your library can make a small change to get the old.
```go
import (
    analytics "github.com/segmentio/analytics-go-old"
)
```

**Comment by f2prateek** [comment]
I'd rather not create a second repo. We'll eventually make the V3 the default starting some point, just not yet....

**Comment by kevpie** [comment]
@f2prateek I really appreciate the responses! Carry on. 👍

**Comment by achille-roussel** [comment]
@f2prateek what do you think about making the README a bit more verbose and explaining that v3 is available? It could give better visibility to make a smoother transition.

**Comment by yields** [comment]
@f2prateek maybe we could add a deprecation log? for it to be less annoying we could log just once when `New()` is called, I suppose that some/most are using vendor so they won't get the deprecation log.

dunno, semver ftw

**Comment by f2prateek** [comment]
Yeah we should do both for those. Once V3 sees more usage too, I want to email all V2 users to upgrade.

 Fwiw Our docs are already using V3 https://segment.com/docs/sources/server/go/ .

**Comment by f2prateek** [comment]
documented steps to take here https://segment.atlassian.net/browse/LIB-262

**Comment by f2prateek** [comment]
Added note in readme https://github.com/segmentio/analytics-go/commit/69984e104a58ead3fc827568403e92f4f066bb13
