### ISSUE TITLE
Async Callback

### ISSUE THREAD

**Issue by achille-roussel** [segmentio/analytics-go#99]
@f2prateek 

I think we should define the policy on how the success and failure callbacks are called. Right now they're triggered from different places in the code, which could end up creating dead locks if the application has locked a resource that its callback would also try to acquire, or just race conditions if the app makes assumptions on what goroutine notifies its callbacks.

Here are few options we can explore:

- Have an internal queue + goroutine that's only in charge of the calling the application's callback so all function calls are made from a single goroutine

- Spawn a new goroutine for every batch of messages we want to notify the application of.

- Use an internal queue + executor so we dispatch callbacks concurrently with a limit on how many goroutines will be created

Whatever option we choose I'll make sure to document it in the `Callback` type.
Let me know if you have other ideas or what sounds the best approach to you.

**Comment by achille-roussel** [comment]
@f2prateek what's your take on that?

**Comment by f2prateek** [comment]
IIRC we've done this language dependendent. On Android/iOS we always do the callback on the main thread, but for Java we leave it undefined. It's the application's responsibility to make sure the callback doesn't block.

**Comment by achille-roussel** [comment]
OK, it seems like not over-engineering this is good, we can still revisit and loosen the requirements later if that's something users will find interesting.

I'll add documentation to make it explicit that there are no guarantees on which goroutine with call the callbacks and they shouldn't make long blocking operations.

Thanks!

**Comment by f2prateek** [comment]
SGTM!
